apiVersion: v1
kind: Template
labels:
  demo: shopping-cicd
  template: shopping-bluegreen
metadata:
  annotations:
    description: This template is a complement to shopping cicd templates
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: shopping-bluegreen
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: shopping-blue
    labels:
      application: shopping
      variant: blue
  spec:
    replicas: 1
    selector:
      deploymentconfig: shopping-blue
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: shopping
          variant: blue
          deploymentconfig: shopping-blue
        name: shopping-blue
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=shopping-blue
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            value: shopping-blue-ns
          - name: MQ_CLUSTER_PASSWORD
            value: 7mzX0pLV03
          - name: JGROUPS_CLUSTER_PASSWORD
            value: CqUo3fYDTv
          - name: AUTO_DEPLOY_EXPLODED
            value: "false"
          image: ' '
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /opt/eap/bin/jboss-cli.sh
                - -c
                - :shutdown(timeout=60)
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          name: shopping
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - shopping
        from:
          kind: ImageStreamTag
          name: shopping:prod-blue
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: shopping
      variant: blue
    name: shopping-blue
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: shopping-blue
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: shopping-green
    labels:
      application: shopping
      variant: green
  spec:
    replicas: 1
    selector:
      deploymentconfig: shopping-green
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: shopping
          variant: green
          deploymentconfig: shopping-green
        name: shopping-green
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=shopping-green
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            value: shopping-green-ns
          - name: MQ_CLUSTER_PASSWORD
            value: 7mzX0pLV03
          - name: JGROUPS_CLUSTER_PASSWORD
            value: CqUo3fYDTv
          - name: AUTO_DEPLOY_EXPLODED
            value: "false"
          image: ' '
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /opt/eap/bin/jboss-cli.sh
                - -c
                - :shutdown(timeout=60)
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          name: shopping
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - shopping
        from:
          kind: ImageStreamTag
          name: shopping:prod-green
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: shopping
      variant: green
    name: shopping-green
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: shopping-green
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      application: shopping
      variant: blue
    name: shopping
  spec:
    alternateBackends:
    - name: shopping-green
      weight: "0"
    to:
      kind: Service
      name: shopping-blue
      weight: "100"
